{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autodeploy-control-plane.runtimeSecretName" . }}
  labels:
    {{- include "autodeploy-control-plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{- if ne ($value | toString) "" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
