{{- if and (eq .Values.workspace.type "persistentVolumeClaim") (not .Values.workspace.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autodeploy-control-plane.fullname" . }}-workspace
  labels:
    {{- include "autodeploy-control-plane.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
  {{- if .Values.workspace.storageClassName }}
  storageClassName: {{ .Values.workspace.storageClassName | quote }}
  {{- end }}
{{- end }}
