apiVersion: v1
kind: Secret
metadata:
  name: autodeploy-control-plane-kubeconfig
type: Opaque
stringData:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: replace-me
        cluster:
          server: https://replace-me:6443
          certificate-authority-data: replace-me
    contexts:
      - name: replace-me
        context:
          cluster: replace-me
          namespace: default
          user: replace-me
    current-context: replace-me
    users:
      - name: replace-me
        user:
          token: replace-me
