apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-web-app.fullname" . }}
  labels:
    {{- include "generic-web-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "generic-web-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ default .Values.container.port .Values.service.targetPort }}
